set -g default-terminal 'tmux-256color'

# ステータスバーをトップに配置する
set-option -g status-position bottom

# 左右のステータスバーの長さを決定する
set-option -g status-left-length 90
set-option -g status-right-length 90

# #H => マシン名
# #P => ペイン番号
# 最左に表示
set-option -g status-left '#S'

# Wi-Fi、バッテリー残量、現在時刻
# 最右に表示
set-option -g status-right ' #(wifi) #(battery --tmux -r) [%Y-%m-%d(%a) %H:%M]'

# ステータスバーを1秒毎に描画し直す
set-option -g status-interval 1

# センタライズ（主にウィンドウ番号など）
set-option -g status-justify centre

# Ctrl+rで設定の更新
bind r source-file ~/.tmux.conf \; display-message "Reload Config!!"

set-option -g mouse on

set-option -g default-command "reattach-to-user-namespace -l zsh"
