set -g default-terminal "tmux-256color"
set -g xterm-keys on

set -g mouse on
set -g status on

setw -g mode-keys vi
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi v send -X begin-selection
bind-key v copy-mode

set -g status-bg "colour238"
set -g status-fg "colour255"
set -g status-position top
set -g history-limit 50000

bind-key r source-file ~/.tmux.conf \; display "Reloaded"

bind -r C-h resize-pane -L 10
bind -r C-j resize-pane -D 10
bind -r C-k resize-pane -U 10
bind -r C-l resize-pane -R 10

# Panes control (これ効かない)
bind-key -n M-Left previous-window
bind-key -n M-Right next-window
# 
bind-key -n M-Up switch-client -p
bind-key -n M-Down switch-client -n

bind -n M-a choose-tree
bind -n M-e choose-session
bind -n M-w choose-tree -w

# Panes control (これ効かない)
bind-key -n S-Left select-pane -L
bind-key -n S-Right select-pane -R
bind-key -n S-Up select-pane -U
bind-key -n S-Down select-pane -D

bind-key u display-popup -d '#{pane_current_path}' -w 90% -h 90% -E
bind-key g display-popup -d '#{pane_current_path}' -w 90% -h 90% -E 'lazygit'

# TPM
set -g @plugin 'tmux-plugins/tpm'

# Theme
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'

run '~/.tmux/plugins/tpm/tpm'
