[[plugins]]
repo = 'Shougo/denite.nvim'

# Goの自動Import
[[plugins]]
repo = 'mattn/vim-goimports'

# 下部 ステータスバー
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'seoul256',
      \ 'active': {
      \   'right': [ [ 'lineinfo' ],
      \              [ 'percent' ],
      \              [ 'fileformat', 'fileencoding', 'filetype', 'charvaluehex' ] ]
      \ },
      \ 'component': {
      \   'charvaluehex': '0x%B'
      \ },
      \ }
'''

# とじかっこ補完
[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = '''
  inoremap <C-l> <C-g>U<Right>
'''

# git の差分
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
	" function s:MoveToFileAtStart()
		" call feedkeys("\<C-w>")
		" call feedkeys("\l")
	" endfunction
	" autocmd VimEnter * NERDTree | call s:MoveToFileAtStart()

	let NERDTreeShowHidden = 1
	nnoremap <silent><C-e> :NERDTreeToggle<CR>
	autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
	let g:NERDTreeDirArrowExpandable = '▸'
	let g:NERDTreeDirArrowCollapsible = '▾'
	nnoremap <C-h> <C-w>h
	nnoremap <C-j> <C-w>j
	nnoremap <C-k> <C-w>k
	nnoremap <C-l> <C-w>l
'''

[[plugins]]
repo = 'preservim/nerdcommenter'
merged = 0
hook_add = '''
	let g:NERDSpaceDelims = 1
	let g:NERDDefaultAlign = 'left'
'''

[[plugins]]
repo = 'cespare/vim-toml'

# 別形式のシンタックスハイライト
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'

# ビューア
[[plugins]]
repo = 'previm/previm'
hook_add = '''
  let g:previm_open_cmd = 'open -a Google\ Chrome'
'''
